version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "CONTAINER_NAME" # Will be updated in codebuild
          ContainerPort: 3030 # application container port exposed from container